replicaCount: 1

image:
  repository: public.ecr.aws/s5b2k5y9/med-app
  pullPolicy: Always
  tag: banhsbao-2022-12-12T14-51-16-602Z

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

extraEnvs:
  - name: PAYPAL_CLIENT_ID
    value: public-med-bucket-v1
  - name: PAYPAL_CLIENT_SECRET
    value: public-med-bucket-v1
  - name: PAYPAL_URL
    value: public-med-bucket-v1
  - name: BUCKET_NAME
    value: public-med-bucket-v1
  - name: DB_USERNAME
    value: root
  - name: DB_PASSWORD
    value: med123456
  - name: DB_DATABASE
    value: pet-view
  - name: DB_HOST
    value: db-med-dev.c60v4o2muaf0.ap-southeast-1.rds.amazonaws.com
  - name: DB_PORT
    value: "3306"
  - name: OPENAI_API_KEY
    value: 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
  - name: MODEL_ENDPOINT
    value: https://api.openai.com/v1/engines/davinci-codex/completions
serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: LoadBalancer
  containerPort: 8088
  targetPort: 8088
  port: 80
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
